### ISSUE TITLE
Nginx not allowing access to posts

### ISSUE THREAD

**Issue by Shourai** [dyutibarma/monochrome#3]
When I change to this theme I am unable to to access the posts.
The homepage does display all of them correctly but when I click a post I get a 404.
Using the standard minima theme this issue does not happen.
Have I configured my nginx wrongly or might this be an issue due to how the url of the posts are?
adding `try_files $uri $uri/ /index.html?$args;` to the location of nginx doesn't give me a 404 anymore. But it doesn't redirect me to the post. The URL changes but I stay on the main page.

EDIT:
I have narrowed it down to: adding a `.html` in the url I am able to access the posts.
Now I have to check how to bypass that.

EDIT2:
changing `permalink: /:title` to `permalink: /:title.html`, works for me. Not sure if this is the correct way to fix this.

**Comment by dyutibarma** [comment]
Not having the .html in the permalink is by design. Maybe something like `try_files $uri $uri/ $uri.html /index.html?$args;` will work.

**Comment by Shourai** [comment]
I can confirm adding `try_files $uri $uri/ $uri.html /index.html?$args;` works.
Thank you very much!
Truly fond of your theme, you should consider putting the theme on rubygems :)
